[package]
name = "mission_control"
version = "0.0.13"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
candid.workspace = true
ic-cdk.workspace = true
ic-cdk-macros.workspace = true
ic-ledger-types.workspace = true
ic-ledger-types-for-canfund = { package = "ic-ledger-types", version = "0.12.0" }
icrc-ledger-types.workspace = true
canfund = "0.4.0"
serde.workspace = true
futures = "0.3.28"
junobuild-shared = { path = "../libs/shared" }
